version: '3.5'

services:
  example-backend:
    image: example-backend
    container_name: example-backend
    environment:
      - REDIS_HOST=example-redis
      - POSTGRES_HOST=example-postgres
      - POSTGRES_PASSWORD=pgsafepw

    depends_on:
      - example-redis
      - example-postgres

  example-frontend:
    image: example-frontend
    container_name: example-frontend

  example-redis:
    image: redis
    container_name: example-redis

  example-postgres:
    image: postgres
    container_name: example-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pgsafepw
    volumes:
      - ./database:/var/lib/postgresql/data

  example-proxy:
    image: nginx
    container_name: example-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80